name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  pack_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm pack
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: afid-*.tgz
